apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-ci-cd-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-ci-cd
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
