apiVersion: v1
kind: Service
metadata:
  name: devops-ci-cd
spec:
  selector:
    app: devops-ci-cd  # This should match the labels in your deployment
  ports:
    - protocol: TCP
      port: 80    # Port inside the cluster
      targetPort: 5000  # The port your app is running on
  type: NodePort   # Expose the service as a NodePort
