name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on any push to the main branch
  pull_request:
    branches:
      - main  # Runs on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checks out your code

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Ensure Python is installed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install all dependencies including pytest

      - name: Run Tests
        run: pytest tests/  # ✅ Runs tests before building the Docker image

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password

      - name: Build Docker Image
        run: |
          docker build -t dockersd12/devops-ci-cd:latest .

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: dockersd12/devops-ci-cd:latest
          exit-code: 1  # Fails pipeline if vulnerabilities are found
          severity: "CRITICAL,HIGH"

      - name: Push Docker Image
        if: success()  # Only push if Trivy scan passes
        run: |
          docker push dockersd12/devops-ci-cd:latest
