name: CI/CD Pipeline for Kubernetes

on:
  push:
    branches:
      - main  # Change this to your branch

jobs:
  build:
    runs-on: ubuntu-latest


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout restart deployment devops-ci-cd
